### PR TITLE
Feature: fixed the linter error and create some new API 

### PR DESCRIPTION
**Pull request by LeeMaster**
### Issues associated with this PR

1. Fix the linter errors
2. Complte accounts and web3 API

### Solutions

too complex to descrbe, you could find the code details in this PR or in my branch 

### UT result

TODO: do the whole UT next PR

### Benchmark

no need benching

### Code Style

Pass golangci-lint checking,  up to now everything is ok.

### CODE REVIEW

**Comment by wujunze** [comment]
Please fix  error   https://github.com/comunion-io/ceres/pull/5/checks?check_run_id=2671030571   @LeeMaster

**Comment by LeeMaster** [comment]
> Please fix error https://github.com/comunion-io/ceres/pull/5/checks?check_run_id=2671030571 @LeeMaster

I think this lint tool is using too strict to this project, `md5.Sum` in my opnion could be passed by this tool, not an error

**Comment by wujunze** [comment]
image

**Comment by LeeMaster** [comment]
@wujunze I have changed the linter config for this PR, because the frontend need the snakelike style variable name,  but in the old configuration, we have set the linter to check the camel style which could cause the CI failed . Because of this thing, I have changed the configuration of golangci-lint. Please approve this PR thx :)

**Review by wujunze — APPROVED** [review]

**Pull request merged**
